name: ag_lib
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  flutter_screenutil:
  flutter_restart: ^0.0.3
  flutter_svg: ^0.19.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/unexpected.svg